/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_juanidiaquez;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanf
 */
public class Lab6P2_JuanIdiaquez extends javax.swing.JFrame {

    /**
     * Creates new form Lab6P2_JuanIdiaquez
     */
    public Lab6P2_JuanIdiaquez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        Botones2 = new javax.swing.ButtonGroup();
        Botones3 = new javax.swing.ButtonGroup();
        Botones4 = new javax.swing.ButtonGroup();
        PopUpAgregarJuego = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NombreAgregarJ = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTAgregarJ = new javax.swing.JTextArea();
        FechaAgregarJ = new com.toedter.calendar.JDateChooser();
        PrecioAgregarJ = new javax.swing.JTextField();
        BotonNuevoAgregarJ = new javax.swing.JRadioButton();
        BotonUsadoAgregarJ = new javax.swing.JRadioButton();
        CantidadDAgregarJ = new javax.swing.JTextField();
        BotonAgregarJuego = new javax.swing.JButton();
        RentableSi = new javax.swing.JRadioButton();
        RentableNo = new javax.swing.JRadioButton();
        AgregadoSi = new javax.swing.JRadioButton();
        AgregadoNo = new javax.swing.JRadioButton();
        PopUpListaJuegos = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaJuegos = new javax.swing.JList<>();
        BotonJuegosListaJuegos = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IdAgregarConsola = new javax.swing.JTextField();
        FabricanteAgregarConsola = new javax.swing.JTextField();
        AñosAgregarConsola = new javax.swing.JTextField();
        PrecioAgregarConsola = new javax.swing.JTextField();
        ModeloAgregarConsola = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BotonPortatil = new javax.swing.JRadioButton();
        BotonEstacionaria = new javax.swing.JRadioButton();
        BotonAgregarConsola = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPortatiles = new javax.swing.JTable();
        SeleccionarListar = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Agregar Juego");

        jLabel10.setText("Nombre");

        jLabel11.setText("Descripcion");

        jLabel12.setText("Fecha de lanzamiento");

        jLabel13.setText("Precio");

        jLabel14.setText("Estado");

        jLabel15.setText("Rentable");

        jLabel16.setText("Agregado");

        jLabel17.setText("Cantidad Disponible");

        NombreAgregarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAgregarJActionPerformed(evt);
            }
        });

        AreaTAgregarJ.setColumns(20);
        AreaTAgregarJ.setRows(5);
        jScrollPane1.setViewportView(AreaTAgregarJ);

        Botones2.add(BotonNuevoAgregarJ);
        BotonNuevoAgregarJ.setText("Nuevo");
        BotonNuevoAgregarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoAgregarJActionPerformed(evt);
            }
        });

        Botones2.add(BotonUsadoAgregarJ);
        BotonUsadoAgregarJ.setText("Usado");
        BotonUsadoAgregarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUsadoAgregarJActionPerformed(evt);
            }
        });

        CantidadDAgregarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadDAgregarJActionPerformed(evt);
            }
        });

        BotonAgregarJuego.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregarJuego.setText("Agregar");
        BotonAgregarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarJuegoMouseClicked(evt);
            }
        });
        BotonAgregarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarJuegoActionPerformed(evt);
            }
        });

        Botones3.add(RentableSi);
        RentableSi.setText("si");
        RentableSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentableSiActionPerformed(evt);
            }
        });

        Botones3.add(RentableNo);
        RentableNo.setText("no");

        Botones4.add(AgregadoSi);
        AgregadoSi.setText("si");

        Botones4.add(AgregadoNo);
        AgregadoNo.setText("no");
        AgregadoNo.setToolTipText("");

        javax.swing.GroupLayout PopUpAgregarJuegoLayout = new javax.swing.GroupLayout(PopUpAgregarJuego.getContentPane());
        PopUpAgregarJuego.getContentPane().setLayout(PopUpAgregarJuegoLayout);
        PopUpAgregarJuegoLayout.setHorizontalGroup(
            PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                        .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(PrecioAgregarJ))
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NombreAgregarJ, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(FechaAgregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(AgregadoSi)
                                .addGap(18, 18, 18)
                                .addComponent(AgregadoNo))
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(CantidadDAgregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(BotonAgregarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                        .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)))
                        .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(RentableSi)
                                .addGap(18, 18, 18)
                                .addComponent(RentableNo))
                            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                                .addComponent(BotonNuevoAgregarJ)
                                .addGap(18, 18, 18)
                                .addComponent(BotonUsadoAgregarJ)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopUpAgregarJuegoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        PopUpAgregarJuegoLayout.setVerticalGroup(
            PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NombreAgregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(FechaAgregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(PrecioAgregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(BotonNuevoAgregarJ)
                    .addComponent(BotonUsadoAgregarJ))
                .addGap(46, 46, 46)
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(RentableSi)
                    .addComponent(RentableNo))
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpAgregarJuegoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(AgregadoSi)
                            .addComponent(AgregadoNo))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopUpAgregarJuegoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAgregarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PopUpAgregarJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CantidadDAgregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        ListaJuegos.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(ListaJuegos);

        BotonJuegosListaJuegos.setText("Select");
        BotonJuegosListaJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonJuegosListaJuegosMouseClicked(evt);
            }
        });
        BotonJuegosListaJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJuegosListaJuegosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lista de Juegos");

        javax.swing.GroupLayout PopUpListaJuegosLayout = new javax.swing.GroupLayout(PopUpListaJuegos.getContentPane());
        PopUpListaJuegos.getContentPane().setLayout(PopUpListaJuegosLayout);
        PopUpListaJuegosLayout.setHorizontalGroup(
            PopUpListaJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpListaJuegosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(BotonJuegosListaJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopUpListaJuegosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        PopUpListaJuegosLayout.setVerticalGroup(
            PopUpListaJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpListaJuegosLayout.createSequentialGroup()
                .addGroup(PopUpListaJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpListaJuegosLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PopUpListaJuegosLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(BotonJuegosListaJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Fabricante");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Años de Uso");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Precio");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Modelo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Agregar Consola");

        PrecioAgregarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioAgregarConsolaActionPerformed(evt);
            }
        });

        ModeloAgregarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloAgregarConsolaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tipo");

        Botones.add(BotonPortatil);
        BotonPortatil.setText("Portatil");
        BotonPortatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPortatilActionPerformed(evt);
            }
        });

        Botones.add(BotonEstacionaria);
        BotonEstacionaria.setText("Estacionaria");

        BotonAgregarConsola.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonAgregarConsola.setText("Agregar");
        BotonAgregarConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarConsolaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PrecioAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FabricanteAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñosAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(BotonPortatil)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEstacionaria))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(ModeloAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(BotonPortatil)
                    .addComponent(BotonEstacionaria))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FabricanteAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñosAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PrecioAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ModeloAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addComponent(BotonAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Agregar consola ", jPanel4);

        TablaPortatiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fabricante", "Años de uso", "Precio", "Modelo", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(TablaPortatiles);

        SeleccionarListar.setText("Seleccionar");
        SeleccionarListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarListarMouseClicked(evt);
            }
        });
        SeleccionarListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(SeleccionarListar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(SeleccionarListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("ListarPortatiles", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addGap(92, 92, 92)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane5)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(574, 574, 574))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarJuegoActionPerformed

    private void NombreAgregarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAgregarJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreAgregarJActionPerformed

    private void CantidadDAgregarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadDAgregarJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadDAgregarJActionPerformed

    private void RentableSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentableSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentableSiActionPerformed

    private void BotonNuevoAgregarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoAgregarJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonNuevoAgregarJActionPerformed

    private void BotonUsadoAgregarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUsadoAgregarJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonUsadoAgregarJActionPerformed

    private void BotonAgregarJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarJuegoMouseClicked
        // TODO add your handling code here:
        String rentabilidad="", Agregado="", estado="";
        String nombre= NombreAgregarJ.getText();
        String descripcion= AreaTAgregarJ.getText();
        Date fecha= FechaAgregarJ.getDate();
        String Precio= PrecioAgregarJ.getText();
        double precio= Double.parseDouble(Precio);
        if (BotonNuevoAgregarJ.isSelected()) {
             estado="nuevo";
        }else if (BotonUsadoAgregarJ.isSelected()) {
             estado="usado";
        }
        if (RentableSi.isSelected()) {
             rentabilidad="si";
        }else if (RentableNo.isSelected()) {
             rentabilidad="no";
        }
        if (AgregadoSi.isSelected()) {
             Agregado= "Si";
        }else if (AgregadoNo.isSelected()) {
              Agregado= "no";
        }
        String CantD= CantidadDAgregarJ.getText();
        int CantidadDisponible= Integer.parseInt(CantD);
        int pos= TablaPortatiles.getSelectedRow();
        Consolas.get(pos).getJuegos().add((new Juego(nombre, descripcion, fecha, precio, estado, rentabilidad, Agregado, CantidadDisponible)));

          if (Consolas.get(pos).getJuegos().size()>0) {
                    DefaultListModel m
                = (DefaultListModel) ListaJuegos.getModel();
        for (int i = 0; i < Consolas.get(pos).getJuegos().size(); i++) {
            m.addElement(Consolas.get(pos).getJuegos().get(i));
        }
        }
 
        
       
        JOptionPane.showMessageDialog(this, "Juego Agregado");
    }//GEN-LAST:event_BotonAgregarJuegoMouseClicked

    private void BotonAgregarConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarConsolaMouseClicked
        Object[]datos=new Object[6];
        String id= IdAgregarConsola.getText();
        int ID= Integer.parseInt(id);
        String fabricante= FabricanteAgregarConsola.getText();
        String añoU= AñosAgregarConsola.getText();
        int AñosUsada= Integer.parseInt(añoU);
        String pesitos= PrecioAgregarConsola.getText();
        double precio= Double.parseDouble(pesitos);
        String modelo=ModeloAgregarConsola.getText();
        if (BotonPortatil.isSelected()) {
            String tamañito=JOptionPane.showInputDialog(null, "agregue el tamaño");
            int tamaño=Integer.parseInt(tamañito);
            String baterillita=JOptionPane.showInputDialog(null, "Agregue el nivel de la bateria");
            int bateria= Integer.parseInt(baterillita);
            String estuche=JOptionPane.showInputDialog(null, "tiene estuche? Marque si o no");
            Consolas.add(new Portatil(tamaño, bateria, estuche, ID, fabricante, AñosUsada, precio, modelo));
            DefaultTableModel m=(DefaultTableModel) TablaPortatiles.getModel();
            for (Consola c : Consolas) {
                
                datos[0]=c.getId();
                datos[1]=c.getFabricante();
                datos[2]=c.getADU();
                datos[3]=c.getPrecio();
                datos[4]=c.getModelo();
                if (c instanceof Portatil) {
                    datos[5]="Portatil";
                }else if (c instanceof Estacionaria) {
                    datos[5]="Estacionaria";
                }
            }
            m.addRow(datos);
        }else if (BotonEstacionaria.isSelected()) {
            String Ncontroles=JOptionPane.showInputDialog(null, "Marque el numero de controles que posee");
            int NumeroCO=Integer.parseInt(Ncontroles);
            String almacenamiento=JOptionPane.showInputDialog(null, "Marque el almacenamiento que posee");
            String TipConex=JOptionPane.showInputDialog(null, "Marque eñ tipo de conexion que tiene");
            Consolas.add(new Estacionaria(NumeroCO, almacenamiento, TipConex, ID, fabricante, AñosUsada, precio, modelo));
             DefaultTableModel m=(DefaultTableModel) TablaPortatiles.getModel();
            for (Consola c : Consolas) {
                datos[0]=c.getId();
                datos[1]=c.getFabricante();
                datos[2]=c.getADU();
                datos[3]=c.getPrecio();
                datos[4]=c.getModelo();
                if (c instanceof Portatil) {
                    datos[5]="Portatil";
                }else if (c instanceof Estacionaria) {
                    datos[5]="Estacionaria";
                }
            }
            m.addRow(datos);
        }
        
        JOptionPane.showMessageDialog(this, "Consola Agregada");
    }//GEN-LAST:event_BotonAgregarConsolaMouseClicked

    private void BotonPortatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPortatilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPortatilActionPerformed

    private void ModeloAgregarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloAgregarConsolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloAgregarConsolaActionPerformed

    private void PrecioAgregarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioAgregarConsolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioAgregarConsolaActionPerformed

    private void SeleccionarListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarListarActionPerformed

    private void SeleccionarListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarListarMouseClicked

          PopUpListaJuegos.pack();
          PopUpListaJuegos.setModal(true);
          PopUpListaJuegos.setLocationRelativeTo(null);
          PopUpListaJuegos.setVisible(true);
    }//GEN-LAST:event_SeleccionarListarMouseClicked

    private void BotonJuegosListaJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJuegosListaJuegosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonJuegosListaJuegosActionPerformed

    private void BotonJuegosListaJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonJuegosListaJuegosMouseClicked
         PopUpAgregarJuego.pack();
          PopUpAgregarJuego.setModal(true);
          PopUpAgregarJuego.setLocationRelativeTo(null);
          PopUpAgregarJuego.setVisible(true);
    }//GEN-LAST:event_BotonJuegosListaJuegosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6P2_JuanIdiaquez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AgregadoNo;
    private javax.swing.JRadioButton AgregadoSi;
    private javax.swing.JTextArea AreaTAgregarJ;
    private javax.swing.JTextField AñosAgregarConsola;
    private javax.swing.JButton BotonAgregarConsola;
    private javax.swing.JButton BotonAgregarJuego;
    private javax.swing.JRadioButton BotonEstacionaria;
    private javax.swing.JToggleButton BotonJuegosListaJuegos;
    private javax.swing.JRadioButton BotonNuevoAgregarJ;
    private javax.swing.JRadioButton BotonPortatil;
    private javax.swing.JRadioButton BotonUsadoAgregarJ;
    private javax.swing.ButtonGroup Botones;
    private javax.swing.ButtonGroup Botones2;
    private javax.swing.ButtonGroup Botones3;
    private javax.swing.ButtonGroup Botones4;
    private javax.swing.JTextField CantidadDAgregarJ;
    private javax.swing.JTextField FabricanteAgregarConsola;
    private com.toedter.calendar.JDateChooser FechaAgregarJ;
    private javax.swing.JTextField IdAgregarConsola;
    private javax.swing.JList<String> ListaJuegos;
    private javax.swing.JTextField ModeloAgregarConsola;
    private javax.swing.JTextField NombreAgregarJ;
    private javax.swing.JDialog PopUpAgregarJuego;
    private javax.swing.JDialog PopUpListaJuegos;
    private javax.swing.JTextField PrecioAgregarConsola;
    private javax.swing.JTextField PrecioAgregarJ;
    private javax.swing.JRadioButton RentableNo;
    private javax.swing.JRadioButton RentableSi;
    private javax.swing.JButton SeleccionarListar;
    private javax.swing.JTable TablaPortatiles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables

ArrayList<Consola>Consolas= new ArrayList();

}
